name: Labels Test

on:
  pull_request:
    branches: [main]
    types:
      [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  assign-labels:
    name: Assign labels from conventional-commits
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    outputs:
      labels-assigned: ${{ steps.action-assign-labels.outputs.labels-assigned }}
      labels-removed: ${{ steps.action-assign-labels.outputs.labels-removed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Execute assign labels
        id: action-assign-labels
        uses: mauroalderete/action-assign-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'fix'
                nouns: ['FIX', 'Fix', 'fix', 'FIXED', 'Fixed', 'fixed']
                labels: ['bug']
              - type: 'feature'
                nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat']
                labels: ['feature']
              - type: 'breaking_change'
                nouns: ['BREAKING CHANGE', 'BREAKING', 'MAJOR']
                labels: ['BREAKING CHANGE']
              - type: 'documentation'
                nouns: ['doc','docu','document','documentation']
                labels: ['documentation']
              - type: 'build'
                nouns: ['build','rebuild']
                labels: ['build']
              - type: 'config'
                nouns: ['config', 'conf', 'cofiguration', 'configure']
                labels: ['config']

  verify-labels:
    runs-on: ubuntu-latest
    name: Verify labels
    needs: assign-labels
    if: github.event.pull_request.merged == false && (needs.assign-labels.outputs.labels-assigned != '[]' || needs.assign-labels.outputs.labels-removed != '[]')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: v0

      - name: Verify labels
        id: action-verify-labels
        uses: ./
        with:
          none: question, wontfix, invalid
          some: bug, feature, BREAKING CHANGE, documentation, build, config
          request-review: true
          request-review-header: '**:bookmark: verify-labels-action**'
          github-token: ${{ secrets.GITHUB_TOKEN }}
